services:
  - type: web
    name: todo-app
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
      cd ..
      npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://chaithuregala123:YssQWYtHfKTcQ8B6@cluster0.zmqjxpt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_ENV
        value: production